version: '3.7'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pr1sm4_Pr1sm4
    volumes:
      - mssql:/var/opt/mssql
    ports:
      - '1433:1433'
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Pr1sm4_Pr1sm4", "-Q", "select 1" ]
      interval: 1s
      retries: 20
      
volumes:
  mssql:
