name: Reproduction

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      
      - name: Original Docker Version
        run: docker version
        
      - name: Start MSSQL
        run: docker-compose -f docker-compose.yml up --detach mssql
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      
      - run: echo "Run prisma introspect with original Docker"
      - name: introspect localhost
        continue-on-error: true
        run: npx prisma introspect
        env:
          DATABASE_URL: sqlserver://localhost:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true
      - name: introspect 127.0.0.1
        continue-on-error: true
        run: npx prisma introspect
        env:
          DATABASE_URL: sqlserver://127.0.0.1:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true

      - run: echo "Downgrade Docker"
      - run: docker-compose down
      - run: sudo apt install moby-engine=19.03.14+azure-1 --allow-downgrades
      - name: Downgraded Docker Version
        run: docker version
      
      - name: Start MSSQL
        run: docker-compose -f docker-compose.yml up --detach mssql
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - run: echo "Run prisma introspect with downgraded Docker"
      - name: introspect localhost
        continue-on-error: true
        run: npx prisma introspect
        env:
          DATABASE_URL: sqlserver://localhost:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true
      - name: introspect 127.0.0.1
        continue-on-error: true
        run: npx prisma introspect
        env:
          DATABASE_URL: sqlserver://127.0.0.1:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true
