name: Reproduction

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose -f docker-compose.yml up --detach mysql
